name: Example Workflow
on: push

jobs:
    obfuscate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Obfuscate with PSU
              uses: psuDevelopment/Obfuscate-With-PSU@main
              id: obfuscate
              with:
                  path: ./Script.lua
                  apiKey: ${{ secrets.PSU_API_KEY }}
            - name: Echo obfuscated file
              run: echo ${{ steps.obfuscate.outputs.file }}
